name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'poetry'
      - name: Install project dependencies
        run: |
          poetry install
      - name: Lint using Flake8
        uses: py-actions/flake8@v2
      - name: Test with pytest
        run: |
          poetry run pytest
